channels:
- conda-forge
dependencies:
- python >=3.10
- cython
- future
- h5py
- holoviews =1.15.2
- ipyparallel
- matplotlib
- moviepy
- nd2reader
- numpy <2.0.0
- numpydoc
- opencv
- peakutils
- psutil
- pynwb
- scikit-image >=0.19.0
- scikit-learn
- scipy
- tensorflow >= 2.4.0
- tifffile
- tqdm
- z5py >= 2.0.15
