name: Linux Conda

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches: [ master ]

jobs:
  build-linux-conda:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python '3.10'
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install mamba
        run: |
          conda install -c conda-forge mamba
          conda clean -a
          
          
          #   - name: install caiman
          #     run: |
          #       mamba install -c conda-forge caiman

      - name: install caiman
        run: |
          mamba env update -n base --file environment.yml
          python setup.py build_ext --inplace
          pip install .
          caimanmanager install

      - name: Test
        run: |
          caimanmanager test